### ISSUE TITLE
EPIC 2 -  Newspaper Work

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#10]
# Summary

This epic will work on implementing the Newspaper Gem, so that this project will have automatic OCR creations.

## Prerequisite:
- [x] Update gitlab with Randy's changes && update hyku
  - [x] MR must be merged into main: https://gitlab.com/notch8/louisville-hyku/-/merge_requests/17

## Spike: ticket #18 
- [x] Review NNP's customizations to the newspaper gem

## Install Newspaper Gem: ticket #19 
- [x] For newspaper works, OCR should get generated upon creation
- [x] Instead of installing the gem directly into this project, pull NNP's customizations into a branch of hyku
- [x] Pull that hyku branch into this project
- [x] Verify OCR automatically generates when creating works

**Comment by orangewolf** [comment]
Linked Items
---
[[3] NEW OCR: Install and enable Newspaper Gem](https://gitlab.com/notch8/louisville-hyku/-/issues/19)

[NEW OCR: Understand work done by NNP](https://gitlab.com/notch8/louisville-hyku/-/issues/18)

[[8] uv is displayed when jpg derivatives are available](https://gitlab.com/notch8/louisville-hyku/-/issues/55)

**Comment by orangewolf** [comment]
Related merge requests
---
[Louisville changes](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/17)
