### ISSUE TITLE
[3] NEW OCR: Install and enable Newspaper Gem

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#108]
- [x] For newspaper works, OCR should get generated upon creation
- [x] OCR should get created from bulkrax and the creation of manual works

## Testing
- [x] Log in as Admin user. When looking at the works page, do you see a download text option?
- [x] Does the universal viewer have the ability to search?
- [x] Can you find a string inside of a document (aka full text search). This will be in the search bar of the home page (not the universal viewer)
- [x] test by creating pdf and jpgs

**Comment by orangewolf** [comment]
Linked Items
---
[EPIC 2 - Newspaper Work](https://gitlab.com/notch8/louisville-hyku/-/issues/26)

**Comment by orangewolf** [comment]
Shana January 2022
---
No code changes have been needed, since pulling in hyku update. Tested on STAGING:

NOTE: The UV is tiny for some reason. However, I was able to OCR functionality by expanding the UV to full screen. 

- [ ] OCR automatically gets created when works are created (manually or via bulkrax). You are able to download various derivatives:


![Image](https://user-images.githubusercontent.com/1054448/204538246-88a58a2c-1e3e-4fd2-9c74-f45faf9964e2.png)



 [txt example](http://lv-hyku-staging.notch8.cloud/downloads/7549c758-79ca-4fe6-b27b-42afcb68519c?locale=en&file=txt)



![Image](https://user-images.githubusercontent.com/1054448/204538281-a096b69f-e93a-4461-926e-5159c261847b.png)




- [ ] We are able to search for OCR text from the home page. It returns relevant works.
Demo: https://share.getcloudapp.com/RBuymY4L 

- [ ] We are able to expand the UV to full screen and search for OCR text in the search bar. If there are results, it will return how many were found within the document and highlight them as well. 

**Search for OCR txt: "Messrs"**



![Image](https://user-images.githubusercontent.com/1054448/204538315-55ee9784-e876-490f-be45-d76fef4c4301.png)

**Comment by orangewolf** [comment]
Crystal January 2022
---
Test with manual upload for a work.

**Comment by orangewolf** [comment]
Summer January 2022
---
I am able to pass this on staging:

I made a work here- https://lv-hyku-staging.notch8.cloud/concern/generic_works/024c40a1-5355-460c-89a5-cc92e2152fc0

uploaded a panera bread menu pdf.

Searched for "Avocado", a string that is contained in the pdf and it returned the work successfully.



![Image](https://user-images.githubusercontent.com/1054448/204538526-96449b82-03bb-4d66-8de3-3550a3239727.png)



### Notch8 QA: Passed

**Comment by orangewolf** [comment]
Rachel February 2022
---
The Leader test in Shana's screenshot doesn't appear to be on this sandbox, so I was unable to test it.

**Comment by orangewolf** [comment]
Rachel February 2022
---
The Cardinal example from 2/18/2022 is great! I only provided a PDF to you for this (although we also have image files for each page). I take it this means that a PDF will suffice? Still trying to determine the best, most efficient approach for upload, since filling in page-level source identifiers and file names for a collection of this size will be arduous if JPEGs are preferred.

**Comment by orangewolf** [comment]
Alisha March 2022
---
@rachel.howard are you ok with closing this? the install does appear to have happened correctly, but we are aware of the uv search issue with ocr and it's being tracked on #90[@rachel.howard](https://github.com/rachel.howard) are you ok with closing this? the install does appear to have happened correctly, but we are aware of the uv search issue with ocr and it's being tracked on [#90 (closed)](https://github.com/notch8/louisville-hyku/-/issues/90)
