### ISSUE TITLE
[5] Import a CSV

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#110]
# story
users ought to be able to upload a csv that has a model with related files, which belongs to a collection.

# acceptance criteria
- [x] a csv with metadata only can be imported successfully
- [x] a csv with metadata where the model belongs to a collection can be imported successfully
- [x] a csv with metadata and file(s) can be imported successfully
- [x] a csv with metadata and files that belong to a collection can be imported successfully
- [x] the work and collection entries say complete and the work/collection are actually created
- [x] the work's show page can be viewed
- [x] the collection's show page can be viewed

# Notes
Files need to be on the server in order to test this with the workflow of our client's. Otherwise, we'd have to use zipped CSV's per bulkrax's [documentation](https://github.com/samvera-labs/bulkrax/wiki/CSV-Importer#files).

**Comment by orangewolf** [comment]
Related Merge Requests
----
[40-import-csv-with-metadata-only](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/28)

[I40 implement related parents field mapping](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/29)


[40 parent child relationships](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/32)

**Comment by orangewolf** [comment]
Alisha January 2022
---
with the work from https://gitlab.com/notch8/louisville-hyku/-/merge_requests/28, we can also upload a work that has files attached to it.

- csv: [Cardinal_Text_With_File.csv](/uploads/a65eda7ff66c0307c3d753b700f5bd48/Cardinal_Text_With_File.csv)
- xml file: [19260924_mets.xml](/uploads/2c3e5308497a1235537457b746610076/19260924_mets.xml)
- there was also a pdf, but it's too large to add as a comment

## notable csv changes
- the "files" column needs to be "file"
- I removed the "CONTENTdm file name" and "CONTENTdm file path" columns entirely. it doesn't correspond to any of the attribute names on a Text model, nor were there files with those names in the given "files" folder.

**Comment by orangewolf** [comment]
Summer February 2022
---
Although the previous file was not successful due to 2 Ldp errors, I was just able to import the Storefronts csv/files which are in a collection, and the works are successfully added to collections:


![Image](https://user-images.githubusercontent.com/1054448/204542395-36c78542-e660-4ed9-bf33-938b2f109277.png)

Importer here:

http://lv-hyku-staging.notch8.cloud/importers/33?locale=en

But, the importer does not say "complete". It is still stuck in a "pending" state. [But, this is being taken care of on another issue](https://gitlab.com/notch8/louisville-hyku/-/issues/7) so I will go ahead and pass this ticket.Importer here:
http://lv-hyku-staging.notch8.cloud/importers/33?locale=en
But, the importer does not say "complete". It is still stuck in a "pending" state. [But, this is being taken care of on another issue](https://gitlab.com/notch8/louisville-hyku/-/issues/7) so I will go ahead and pass this ticket.

**Comment by orangewolf** [comment]
Rachel February 2022
---
The "Pending" message has been plaguing us with all of our uploads.

**Comment by orangewolf** [comment]
Shana February 2022
---
Hi @rachel.howard The status stuck on Pending should've been fixed last week. Let me know if you are seeing otherwise. The fix went into bulkrax and we upgraded this project's bulkrax again, to receive it. You may need to re run an importer to see it update, or create a new one and disregard the rest.

also, if you were testing with this [importer](http://lv-hyku-staging.notch8.cloud/importers/30?locale=en), it isn't going to work because the dev app is hosted on a different server than your prod. It doesn't have a path/file that matches "/media/hykuimports/simmons/simmons_images.csv". It remains pending because sidekiq (the background job that runs the imports) tries to find that file over and over again.Hi [@rachel.howard](https://github.com/rachel.howard) The status stuck on Pending should've been fixed last week. Let me know if you are seeing otherwise. The fix went into bulkrax and we upgraded this project's bulkrax again, to receive it. You may need to re run an importer to see it update, or create a new one and disregard the rest.
also, if you were testing with this [importer](http://lv-hyku-staging.notch8.cloud/importers/30?locale=en), it isn't going to work because the dev app is hosted on a different server than  your prod. It doesn't have a path/file that matches "/media/hykuimports/simmons/simmons_images.csv".  It remains pending because sidekiq (the background job that runs the imports) tries to find that file over and over again.
