### ISSUE TITLE
[5] Enable Universal Viewer

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#111]
# summary
return the uv viewer

# acceptance criteria
- [x] A work's show page should display a universal viewer if a jpg is the first attached file
- [x] the uv should look the same as it does on the screenshot below
  - search bar
  - settings options on the top right
  - options for thumbnails on the left
- [ ] ~~retain the navigation options in mobile view~~ (Out of scope, per Crystal)
 
# expected behavior

![Image](https://user-images.githubusercontent.com/1054448/204552323-604e7930-9a40-4ed9-965a-91c5f99b4d80.png)

# resources
- https://playbook-staging.notch8.com/en/samvera/hyrax/how_to/add-universal-viewer
- https://playbook-staging.notch8.com/en/samvera/universal-viewer/uv-in-blacklight
- https://playbook-staging.notch8.com/e/en/samvera/universal-viewer/related-merge-requests

**Comment by orangewolf** [comment]
Related Merge Requests
---
[UV Missing Files](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/26)

[i38 - add missing UV stylesheet from nnp](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/30)

**Comment by orangewolf** [comment]
Alisha January 2022
---
ref !26 

# expected behavior
- the uv viewer should show on a work show page that has a jpg attached
  - if a pdf was uploaded first, the work needs to be edited to reflect the same jpg as the thumbnail, rendering and representative media

# todo
- correct the styling of the uv

# demo


![Image](https://user-images.githubusercontent.com/1054448/204552820-4ea7466d-1b74-4d45-87f0-5a0f659afd4f.png)

**Comment by orangewolf** [comment]
Rachel February 2022
---
I'm not seeing the UV on staging -can you point me to the example there?
