### ISSUE TITLE
[2] importer default admin set

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#142]
# Summary
a user needs to be able to select an admin set when creating/updating an importer

# Acceptance Criteria

* [ ] there is at least one admin set option available when creating a new importer
* [ ] there is at least one admin set option available when updating an existing importer

# Screenshots or Video

![Image](https://user-images.githubusercontent.com/1054448/205053317-0f004452-cca6-4f71-a713-28c08542daee.png)

# Testing Instructions
Url: /importers/new?locale=en
* select the "administrative set" drop down and confirm a selection can be made

**Comment by orangewolf** [comment]
Linked Items
---
[EPIC 1 - BULKRAX && TESTING](https://gitlab.com/notch8/louisville-hyku/-/issues/25)

**Comment by orangewolf** [comment]
Related Merge Requests
---
[28-default-admin-set](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/24)

**Comment by orangewolf** [comment]
Alisha January 2022
---
ref !24

# expected behavior
- the admin@notch8.com user should have access to the default admin set on single.hyku.test

this should be set with the seeds, but if not I updated the "troubleshooting" steps on the repo readme. for some reason, this is only an problem with the single.hyku.test tenant.

# demo


![Image](https://user-images.githubusercontent.com/1054448/205053541-3e8b19b8-7df9-4056-b100-9d3b09c75f80.png)

**Comment by orangewolf** [comment]
Summer February 2022
---
Tested on staging:

<details>

![Screen_Shot_2022-02-01_at_8.30.46_AM](/uploads/cfeb63f26b88e2f8ac47b4a5c3ac4575/Screen_Shot_2022-02-01_at_8.30.46_AM.png)

![Screen_Shot_2022-02-01_at_8.30.28_AM](/uploads/ef68da38cae0bf35249646de0281a996/Screen_Shot_2022-02-01_at_8.30.28_AM.png)

</details>


* [ ] there is at least one admin set option available when creating a new importer
* [ ] there is at least one admin set option available when updating an existing importer

### Notch8 QA: Passed

**Comment by orangewolf** [comment]
Rachel February 2022
---
The Default Admin set was there, but when I tried a test import, I got a "We're sorry, but something went wrong.
If you are the application owner check the logs for more information." error.

**Comment by orangewolf** [comment]
Shana March 2022
---
After running seeds, try the following if the default admin set still doesn't exist: 

1. Get inside of rails console
1. **Do not** switch into a tenant
1. user = User.find_by(email: '[client@example.com](mailto:client@example.com)')
1. user.add_role(:registered)
1. user.add_role(:admin)
1. refresh your browser and/or login/out/in again.
