### ISSUE TITLE
Bulkrax upgrade to v.2

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#151]
# Summary

Dev Note: To be done after the latest Bulkrax version has been released.

Bulkrax will be releasing version 2 soon. Once done, we need to upgrade the app to use the new version so that we can use the refactored parent/child relationships work

* [x] Upgrade bulkrax to use the latest version.
* [ ] Confirm basic functionality: Verify that bulkrax successfully imports CSVs and creates collections for the works.
* [ ] Take note of any breaking changes

# Acceptance Criteria

* [ ]

# Screenshots or Video
<details>
<summary></summary>

</details>

# Testing Instructions
Url:
*

# Notes
## Engineering Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by orangewolf** [comment]
Linked Items
---
[EPIC 1 - BULKRAX && TESTING](https://gitlab.com/notch8/louisville-hyku/-/issues/25)

**Comment by orangewolf** [comment]
Diem January 2022
---
**This passes Notch8 QA.** See attached screenshot.
<details><summary>Summer has specified that this ticket simply upgrades Bulkrax to 2.0 and that complete Bulkrax integration will occur later. The Gemfile.lock shows that Bulkrax has been upgraded to 2.0</summary>![Gemfile.lock___louisville-hyku_2022-01-20_at_4.48.37_PM](/uploads/49f2f5c21d253b8e44066ab1cdb10e7d/Gemfile.lock___louisville-hyku_2022-01-20_at_4.48.37_PM.jpg)</details>
