### ISSUE TITLE
NEW OCR: Understand work done by NNP

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#156]
- [ ] Find and review the NNP[ PRs ](https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/293/diffs#c101566231f001be4bbbac66eea2a0372daa8a0d)related to installing the newspaper gem. 
- [ ] Meet with Rob for a code walk through. (1/13/22 3:30PM)
- [ ] Lay out details for implementation in Louisville. Rob suggests pushing NNP's work into Hyku, and then pulling down Hyku for this project.

**Comment by orangewolf** [comment]
Linked Items
---
[EPIC 2 - Newspaper Work](https://gitlab.com/notch8/louisville-hyku/-/issues/26)

**Comment by orangewolf** [comment]
Related Merge Requests
---
[Set up OCR per file, in viewer search and creates derivatves PDFs if imaages are uploaded.](https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/293)
