### ISSUE TITLE
Bulkrax: Create release notes

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#158]
Create release notes for the latest bulkrax, in preparation of releasing a new version. Include: 

- [x] Change Log: Review and note all of the PRs since the last release/version
- [x] Features: List description of added features
- [x] Bug Fixes: Describe any patches
- [x] Breaking Changes: Note any breaking changes

Note: Get support from team to help fill in the details.

**Comment by orangewolf** [comment]
Linked Items
---
[EPIC 1 - BULKRAX && TESTING](https://gitlab.com/notch8/louisville-hyku/-/issues/25)

**Comment by orangewolf** [comment]
Shana January 2022
---
WIP Docs c/o @summer-cook 

1. Draft notes: https://docs.google.com/document/d/1HX2lZBgIo3hurS-Ul6Jv5qSBU1IvQ2zUAV8g3B4HoiY/edit
2. PRs since Aug 18, 2021: https://docs.google.com/spreadsheets/d/1VmmhFhZBUJHt59poHB10W-OfbMKc2p938yOBtJ4kVk0/edit#gid=0
