### ISSUE TITLE
Bulkrax: Upgrade Bulkrax gem

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#8]
Dev Note: To be done after the latest Bulkrax version has been released.

- [ ] Upgrade bulkrax to use the latest version. 
- [ ] Confirm basic functionality: Verify that bulkrax successfully imports CSVs and creates collections for the works.
- [ ] Take note of any breaking changes
