### ISSUE TITLE
EPIC 1 - BULKRAX && TESTING

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#9]
# Summary 

- This epic will work on enabling and upgrading Bulkrax to 2.0. 
- It will also get a baseline of testing current functionalities and concerns. Will the hyku upgrade resolve these issues?

## Prerequisite:
- [x] Bulkrax 2.0 release
- [x] Randy's changes - he pushed a newer version of their code to github per [1/13 meeting](https://gitlab.com/notch8/louisville-hyku/-/issues/17) that we need to pull down into gitlab
  - [x] MR: https://gitlab.com/notch8/louisville-hyku/-/merge_requests/17
- [x] Hyku Upgrade
  - [x] MR: https://gitlab.com/notch8/louisville-hyku/-/merge_requests/17

## Create release notes: ticket [#15](https://gitlab.com/notch8/louisville-hyku/-/issues/15)
* [x] Change Log: Review and note all of the PRs since the last release/version
* [x] Features: List description of added features
* [x] Bug Fixes: Describe any patches
* [x] Breaking Changes: Note any breaking changes

## Upgrade Bulkrax to v2.0: ticket [#17](https://gitlab.com/notch8/louisville-hyku/-/issues/17)
Note: To be done after the latest Bulkrax version has been released.
* [x] Upgrade bulkrax to use the latest version.
* [x] Confirm basic functionality: Verify that bulkrax successfully imports CSVs and creates collections for the works.

## Implement Parent/Child relationships: ticket [#21](https://gitlab.com/notch8/louisville-hyku/-/issues/21) 
* [ ] Successfully importing a CSV will result in the creation of Works linked to the children, if noted in the CSV's 'children' column.
  - docs: https://github.com/samvera-labs/bulkrax/wiki/Configuring-Bulkrax#related_children_field_mapping

## QA Existing Issues: Are these errors still happening?
Note: To be done after this [MR](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/17) has successfully been merged into main
- [ ] "Your Collections are unavailable" error: ticket #5 
- [ ] Images not showing after import: ticket #8 
- [ ] Job Wrapper: ticket #9 
- [ ] LDP Errors on Bulkrax: ticket #10 
- [ ] Bulkrax's pending status bug: ticket #7 

## Hyku upgrade deploy test with Randy: ticket #13

**Comment by orangewolf** [comment]
Related Merge Requests
---
[Louisville changes](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/17)
