### ISSUE TITLE
[8] uv is displayed when jpg derivatives are available

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/louisville-hyku#94]
# story
thumbnails and the uv ought to always show after an import

# acceptance criteria
- [ ] a work ought to show the uv by default if the work has a jpg attached
- [ ] a work ought to show the first jpg attached, as the thumbnail
- [ ] a parent work without jpg's attached ought to show the uv by default if any of its child works have a jpg attached
- [ ] a parent work without jpg's attached ought to show the first jpg on the first child work as its thumbnail

**Comment by orangewolf** [comment]
Linked Items 
---
[EPIC 2 - Newspaper Work](https://gitlab.com/notch8/louisville-hyku/-/issues/26)

**Comment by orangewolf** [comment]
Related Merge Requests
---
[55-default-uv-and-thumbnail](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/40)

[55-always-display-uv-on-parent](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/44)

[55-update-manifest](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/51)

[Draft: 55-set-parent-thumbnail](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/54)

[tmp-show-all-child-works](https://gitlab.com/notch8/louisville-hyku/-/merge_requests/57)

**Comment by orangewolf** [comment]
Alisha February 2022
---
ref [!40 (merged)](https://github.com/notch8/louisville-hyku/-/merge_requests/40)

# expected behavior
- set the work thumbnail and representative image on import

# demo


https://user-images.githubusercontent.com/1054448/204271567-5f01487a-9486-46d3-8194-a4d3949f1da7.mp4



# resources
- https://gitlab.com/notch8/newman-numismatic-portal/-/blob/main/app/actors/hyrax/actors/file_set_actor.rb#L80

**Comment by orangewolf** [comment]
Alisha February 2022
---
found another circumstance that needs to be accounted for.

if a parent model is uploaded without an attached file, but it has children with attached files...the uv does not show.
- selecting an image to be the thumbnail and representative image from the fileset manager sets those values...but the uv still doesn't show
- tested the values in the iiif_viewer? method:
  ``` ruby
  representative_id.present? => true
  representative_presenter.present? => true
  Hyrax.config.iiif_image_server? => true
  representative_presenter.image? => true
  members_include_viewable_image? => false
  ```

**Comment by orangewolf** [comment]
Alisha February 2022
---
discussed this in the client meeting today. if the parent doesn't have an attached file(which will almost always be the case), they would like the uv to default to the file attached on the first image.

**Comment by orangewolf** [comment]
Alisha February 2022
---
ref !44ref [!44 (merged)](https://github.com/notch8/louisville-hyku/-/merge_requests/44)

co-author: braydon justice <braydon@scientist.com>

# Screenshots / Video


https://user-images.githubusercontent.com/1054448/204271924-6d805b36-8eb0-4074-ad36-361eac4a0e88.mp4



# Expected Behavior
- the uv will show on a parent work show page if it, or any of its children, has a jpg file attached
- the uv seems to hold the child works themselves, not the jpg's. so every time you click on the name of a child in the uv, the uv refreshes and shows each one independently

# todo
- edit the manifest so that the children jpgs show up all together in the same rendering of the uv

**Comment by orangewolf** [comment]
Alisha February 2022
---
ref !51ref [!51 (merged)](https://github.com/notch8/louisville-hyku/-/merge_requests/51)

co-author: shana moore <shana@scientist.com><br>
co-author: summer cook <summer@scientist.com><br>
co-author: sara g <sara@scientist.com><br>
co-author: rob kaufman <rob@scientist.com>

# Screenshots / Video


![Image](https://user-images.githubusercontent.com/1054448/204272131-eff9e866-e024-4401-8eb1-ae73939e0231.png)



# Expected Behavior
- child work images show as canvases in the parent work manifest
- child work images show in the uv on the parent show page

**Comment by orangewolf** [comment]
Alisha February 2022
---
created [importer 18](http://lv-hyku-staging.notch8.cloud/importers/18?locale=en) which has a parent work (with no attached files) and 3 child works (each with 1 attached jpg).

the parent show page renders the uv with an image for each of the associated 3 children. each child work also shows in the "items" section. you can click each child work and be taken to its individual show page.

caveat: there's a bulkrax update being worked on related to the CreateRelationshipsJob. in the meantime, the child works _may_ not show in their intended order.



![Image](https://user-images.githubusercontent.com/1054448/204272314-b9a888c2-77b8-4e17-a0ad-ee675c39ebad.png)




![Image](https://user-images.githubusercontent.com/1054448/204272363-6f7c08e5-9e71-4400-8cb9-9faf85e18dfd.png)
